In [1]:
import numpy as np

In [2]:
# VECTOR OPERATION

In [3]:
u = np.array([2,4,5,6])

In [9]:
2 * u

array([ 4,  8, 10, 12])

In [10]:
v = np.array([1,0,0,4])

In [11]:
v

array([1, 0, 0, 4])

In [12]:
u + v

array([ 3,  4,  5, 10])

In [13]:
u * v

array([ 2,  0,  0, 24])

In [15]:
# MULTIPLICATION

In [18]:
v.shape[0]

4

In [22]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result
    

In [23]:
vector_vector_multiplication(u,v)

np.float64(26.0)

In [24]:
u.dot(v)

np.int64(26)

In [25]:
# MATRIX VECTOR MULTIPLICATION

In [26]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [27]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [30]:
U.shape

(3, 4)

In [38]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [39]:
matrix_vector_multiplication(U,v)

array([26.,  9.,  7.])

In [40]:
U.dot(v)

array([26,  9,  7])

In [41]:
# MATRIX MATRIX MULTIPLICATION

In [42]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [ ]:
def matrix_matrix_multiplication(U,V)
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        
        